feat: add prettier eslint config

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,7 +7,7 @@ name: Deploy Next.js site to Pages
 on:
   # Runs on pushes targeting the default branch
   push:
-    branches: ["master"]
+    branches: ['master']
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -21,7 +21,7 @@ permissions:
 # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
 # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
 concurrency:
-  group: "pages"
+  group: 'pages'
   cancel-in-progress: false
 
 jobs:
@@ -31,23 +31,23 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-#      - name: Detect package manager
-#        id: detect-package-manager
-#        run: |
-#          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-#            echo "manager=yarn" >> $GITHUB_OUTPUT
-#            echo "command=install" >> $GITHUB_OUTPUT
-#            echo "runner=yarn" >> $GITHUB_OUTPUT
-#            exit 0
-#          elif [ -f "${{ github.workspace }}/package.json" ]; then
-#            echo "manager=npm" >> $GITHUB_OUTPUT
-#            echo "command=ci" >> $GITHUB_OUTPUT
-#            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-#            exit 0
-#          else
-#            echo "Unable to determine package manager"
-#            exit 1
-#          fi
+      #      - name: Detect package manager
+      #        id: detect-package-manager
+      #        run: |
+      #          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+      #            echo "manager=yarn" >> $GITHUB_OUTPUT
+      #            echo "command=install" >> $GITHUB_OUTPUT
+      #            echo "runner=yarn" >> $GITHUB_OUTPUT
+      #            exit 0
+      #          elif [ -f "${{ github.workspace }}/package.json" ]; then
+      #            echo "manager=npm" >> $GITHUB_OUTPUT
+      #            echo "command=ci" >> $GITHUB_OUTPUT
+      #            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+      #            exit 0
+      #          else
+      #            echo "Unable to determine package manager"
+      #            exit 1
+      #          fi
 
       - name: Setup pnpm
         uses: pnpm/action-setup@v2.2.4
@@ -59,8 +59,6 @@ jobs:
         with:
           node-version: 20
           cache: 'pnpm'
-
-
 
       - name: Setup Pages
         uses: actions/configure-pages@v3
